language: node_js
node_js:
- 7
- 6
cache:
  yarn: true
deploy:
  provider: npm
  email: jeantsai@qq.com
  api_key:
    secure: RUGHQvqibwEXlXcwe6wLdm6xjrmacX4CtbZi5OGekdWJM4xN+W/cli8/MOhmPyNfq7dk1TE/U6WQwDJ/DcvDPUJESe0u7fNBKsuZvClvb67tZFBQZfI7WyNXE9eMspOFG1R9yw0vh5u8AJNuRHmOMqE13Uk4/J4y9yAV594Gynh6YtQlwLMi5CmB98qfSjAaQu/hcjci8BFtuTcfmTk2Nal2pxI83cV+juijFPeuBhZ8xiQywRXFZQ08E9eU6AOH7u09CU850qR6jX9dr85IMTihSF+yMAlVTVWeemIuus1NSEezC48AdPFX80QQOVPD4JGpe76aNuDz9N4hC7HgDsr9cuP7klbWegGlUh0S+V6VS5SnJWEIk7pi6ClorbHWIMA6kwxicb2OKywudqzLw+C7Lhb+YBsPyjkchXa6vwNVdBeR3R78EMI8qOEL3u78k3PQfh5Jsq5dqIHQaTD6Qqb1qy5H7eBjcWkIjcCz44jJGwg0aaCz+dJrWyVXP1xtHtCfiAvLfNNHn3P4p+PsnJdvrqktlgY5vSgC6Y2BShObGivJwWOH/gyG+PZ2T8rftLUmfsg8IwvPYce4Iuhei3H8znZC2ciyDw1YlpMXPvC135KPjixvCE1I3V8ChTmKxTlZHGnHT067clZo/Ay0yjhXmsH/w8O2xNoB11ajE58=
  on:
    tags: true
    repo: jeantsai/generator-jhipster-circlecici-2
